version: "3"
services:
    sillytavern:
        build: ..
        container_name: sillytavern
        hostname: sillytavern
        image: sillytavern/sillytavern:latest
        ports:
            - "8000:8000"
        volumes:
            - "./config:/home/node/app/config"
        restart: unless-stopped
