name: Rust Build and Release
on: push
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
                rust:
                    - stable
        defaults:
            run:
                working-directory: setup
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies (Ubuntu)
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt-get update && sudo apt-get install -y libatk1.0-dev

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.rust }}
                  override: true
            - name: Build
              run: cargo build --release --verbose
            - name: Upload artifact (Linux & macOS)
              if: matrix.os != 'windows-latest'
              uses: actions/upload-artifact@v2
              with:
                  name: setup-${{ matrix.os }}
                  path: target/release/setup
            - name: Upload artifact (Windows)
              if: matrix.os == 'windows-latest'
              uses: actions/upload-artifact@v2
              with:
                  name: setup-${{ matrix.os }}.exe
                  path: target/release/setup.exe
    release:
        needs: build
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: setup
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v2
              with:
                  path: artifacts
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  TOKEN: ${{ secrets.TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false
            - name: Upload Release Asset (Linux & macOS)
              if: contains(matrix.os, 'windows') == false
              uses: actions/upload-release-asset@v1
              env:
                  TOKEN: ${{ secrets.TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./artifacts/setup-${{ matrix.os }}
                  asset_name: setup-${{ matrix.os }}
                  asset_content_type: application/octet-stream
            - name: Upload Release Asset (Windows)
              if: contains(matrix.os, 'windows')
              uses: actions/upload-release-asset@v1
              env:
                  TOKEN: ${{ secrets.TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./artifacts/setup-${{ matrix.os }}.exe
                  asset_name: setup-${{ matrix.os }}.exe
                  asset_content_type: application/octet-stream
